### ISSUE TITLE
数据源2无法查询排名/公会等，但是可以查询档线

### ISSUE THREAD

**Issue by ghost** [pcrbot/clan_search_tw#10]
socket.gaierror: [Errno -5] No address associated with hostname

urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f6c012e1af0>: Failed to establish a new connection: [Errno -2] Name or service not known

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='layvtwt.top', port=443): Max retries exceeded with url: /current/getalltime/tw (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa2c83d4dc0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='layvtwt.top', port=443): Max retries exceeded with url: /current/getalltime/tw (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa2c83d4dc0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

同时服务器无法ping通该域名，猜测也许是其拒绝境外ip访问连接导致，但这又与能查档线不符合...

**Comment by azmiao** [comment]
> socket.gaierror: [Errno -5] No address associated with hostname
> 
> urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f6c012e1af0>: Failed to establish a new connection: [Errno -2] Name or service not known
> 
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='layvtwt.top', port=443): Max retries exceeded with url: /current/getalltime/tw (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa2c83d4dc0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
> 
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='layvtwt.top', port=443): Max retries exceeded with url: /current/getalltime/tw (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa2c83d4dc0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
> 
> 同时服务器无法ping通该域名，猜测也许是其拒绝境外ip访问连接导致，但这又与能查档线不符合...

尝试在`search.py`的第30行和31行之间，加上
`    elif source == 'layvtwt.top':
        source = 'rank.' + source`
，不知道是不是这个问题导致的，但我自己测试和前川未来使用的时候倒是没有遇到你这个问题，蛮怪的😂

**Comment by azmiao** [comment]
关于Ping的问题，我这边也是ping不通`rank.layvtwt.top`的，但是能够浏览器打开，因此我怀疑是他截断了ICMP报文，以防dos攻击

**Comment by azmiao** [comment]
关于Ping的问题，我这边也是ping不通`rank.layvtwt.top`的，但是能够浏览器打开，因此我怀疑是他截断了ICMP报文，以防dos攻击

**Comment by ghost** [comment]
已经可以了，感谢帮助解决问题
