### ISSUE TITLE
我那边新增了个全服排名统计，可以考虑加一个（

### ISSUE THREAD

**Issue by layvsan** [pcrbot/clan_search_tw#11]
如题，虽然没啥卵用，但是也确实没啥卵用

**Comment by azmiao** [comment]
是指统计历史排名吗

**Comment by layvsan** [comment]
> 

不是，区服选择里加了个第五项，统计了4个服务器的总排名数据，你看看就知道了

**Comment by azmiao** [comment]
> > 
> 
> 不是，区服选择里加了个第五项，统计了4个服务器的总排名数据，你看看就知道了

没找到你的仓库

**Comment by layvsan** [comment]
> 是指统计历史排名吗

接口增加了个/tw/merge，预定这个月再加个分数变动，可以用来猜猜是不是结刀了（虽然还是没啥屌用的功能

**Comment by azmiao** [comment]
> 

哦，是说网页啊2333

**Comment by azmiao** [comment]
az，我去看看

**Comment by azmiao** [comment]
大概是搞定了，顺便重构了下代码，原来写的屎山太烂了
